define(["core/class", "ui/ui", "system/security", "util/util", "util/message", "util/http", "language/language", "manager/manager", "manager/report/report", "system/log"], (function(a, e, t, i, n, o, l, d, r, s) {
    "use strict";
    return e = new e,
    i = new i,
    o = new o,
    n = new n,
    l = new l,
    d = new d,
    r = new r,
    s = new s,
    a.extend({
        path: i.apiPath + "api/Manager/",
        providerPath: i.apiPath + "api/Provider/",
        leaguePath: i.apiPath + "api/League/",
        customerReportPath: i.apiPath + "api/Report/",
        customerPath: i.apiPath + "api/Customer/",
        ID: 0,
        lib: i.apiPath + "api/lib/",
        componentPath: "manager/module/customer-admin/",
        module: "player-info",
        msgNotChange: "Change not saved!  This customer is not under the current agent. Please check the agent listed at the top right of your screen.",
        info: {},
        total: {
            WIN: 0,
            RISK: 0
        },
        rows: {
            count: 0,
            data: [],
            limit: 50
        },
        player: {},
        amounts: {
            Balance: 0,
            Available: 0
        },
        weeklyFlag: !1,
        propListHide: [],
        casinoID: 0,
        section: "player-info",
        init: function() {},
        listeners: function() { /* ...existing code... */ },
        getHorseRules: function(a) { /* ...existing code... */ },
        verifyZero: function(a) { /* ...existing code... */ },
        getEZLimits: function(a) { /* ...existing code... */ },
        saveEZLimit: function() { /* ...existing code... */ },
        getPropLimits: function(a) { /* ...existing code... */ },
        getLiveCasinoLimits: function(a) { /* ...existing code... */ },
        getFreshdeckCasinoLimits: function(a) { /* ...existing code... */ },
        savePropLimit: function() { /* ...existing code... */ },
        saveLiveCasinoLimit: function() { /* ...existing code... */ },
        saveFreshdeckCasinoLimit: function() { /* ...existing code... */ },
        getCasinoLimit: function(a) { /* ...existing code... */ },
        getCasinoLimitAmigo: function(a) { /* ...existing code... */ },
        getHidelinesOptions: function(a) { /* ...existing code... */ },
        getEarlyLimitOptions: function(a) { /* ...existing code... */ },
        getEarlyLimit: function(a) { /* ...existing code... */ },
        saveEarlyLimit: function() { /* ...existing code... */ },
        getPropSetting: function(a) { /* ...existing code... */ },
        savePropSetting: function() { /* ...existing code... */ },
        getSoccerSetting: function(a) { /* ...existing code... */ },
        showSoccerMajorLeagues: function() { /* ...existing code... */ },
        processSoccerSettings: function() { /* ...existing code... */ },
        saveSoccerSetting: function() { /* ...existing code... */ },
        checkSavingTime: function(a) { /* ...existing code... */ },
        validSavePropSetting: function() { /* ...existing code... */ },
        validSaveSoccerSetting: function() { /* ...existing code... */ },
        checkDataField: function({value: a}) { /* ...existing code... */ },
        saveCasinoLimit: function() { /* ...existing code... */ },
        saveCasinoLimitAmigo: function() { /* ...existing code... */ },
        tabsGeneralListners: function() { /* ...existing code... */ },
        switchActions: function(a, e) { /* ...existing code... */ },
        tapAuthorization: function() { /* ...existing code... */ },
        get: function(a) { /* ...existing code... */ },
        set: function(a) { /* ...existing code... */ },
        setWeeklyBack: function() { /* ...existing code... */ },
        setAnalysisBack: function() { /* ...existing code... */ },
        setCustomerAdminBack: function(a) { /* ...existing code... */ },
        authorizations: function() { /* ...existing code... */ },
        data: function(a) { /* ...existing code... */ },
        getCryptoInfo: function(a) { /* ...existing code... */ },
        getAgentInfo: function(a) { /* ...existing code... */ },
        save: function() { /* ...existing code... */ },
        setTransaction: function() { /* ...existing code... */ },
        listenersAddTransaction: function() { /* ...existing code... */ },
        preSetTransaction: function() { /* ...existing code... */ },
        updateBuyPoints: function() { /* ...existing code... */ },
        setParlayLimits: function() { /* ...existing code... */ },
        setTeaserLimits: function() { /* ...existing code... */ },
        flagVerify: function(a) { /* ...existing code... */ },
        updateByColumn: function(a) { /* ...existing code... */ },
        updateByColumnChecked: function(a) { /* ...existing code... */ },
        ifNull: function(a) { /* ...existing code... */ },
        getTeaserTiesDesc: function(a) { /* ...existing code... */ },
        getTeaserLimits: function() { /* ...existing code... */ },
        getTeaserSportSpecs: function(a) { /* ...existing code... */ },
        getTeaserPayCard: function(a) { /* ...existing code... */ },
        deleteMessage: function(a) { /* ...existing code... */ },
        getMail: function(a) { /* ...existing code... */ },
        getTeaserProfile: function() { /* ...existing code... */ },
        getParlayPayCard: function() { /* ...existing code... */ },
        getPointBuying: function(a) { /* ...existing code... */ },
        getParlayLimits: function() { /* ...existing code... */ },
        setSource: function() { /* ...existing code... */ },
        table: function(a) { /* ...existing code... */ },
        row: function(a) { /* ...existing code... */ },
        updatePassword: function(a) { /* ...existing code... */ },
        updateCreditLimit: function(a) { /* ...existing code... */ },
        updateWagerLimit: function(a) { /* ...existing code... */ },
        updateFlag: function(a) { /* ...existing code... */ },
        updateMaster: function(a) { /* ...existing code... */ },
        saveTransaction: function(a) { /* ...existing code... */ },
        setNewTransaction: function(a) { /* ...existing code... */ },
        getHistory: function(a) { /* ...existing code... */ },
        sethistory: function(a) { /* ...existing code... */ },
        getUIForm: function(a) { /* ...existing code... */ },
        configComponenTabs: function() { /* ...existing code... */ },
        getListAgentsByAgent: function(a) { /* ...existing code... */ },
        setListAgentsByAgent: function(a) { /* ...existing code... */ },
        getList: function(a) { /* ...existing code... */ },
        setPlayers: function(a) { /* ...existing code... */ },
        sendEZWebSocket: function(a) { /* ...existing code... */ }
    })
}
));
